//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Cust
    {
        public int ID { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Phone { get; set; }
        public string Cust_Email { get; set; }
        public byte[] Cust_image { get; set; }
    }
}
